---
- name: create directory "{{ firefox_path }}"
  file:
    state: directory
    path: "{{ firefox_path }}"

- name: copy profiles.ini
  template:
    src: templates/profiles.ini.j2
    dest: "{{ firefox_path }}/profiles.ini"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

# make sure directories for the addons exist
- name: create project directory "{{ profile_path }}/extensions"
  file:
    state: directory
    path: "{{ profile_path }}/extensions"

- name: create project directory {{ profile_path }}/browser-extension-data
  file:
    state: directory
    path: "{{ profile_path }}/browser-extension-data"

# UBlock Origin
- name: Install ublock origin
  block:
    - file:
        state: directory
        path: "{{ profile_path }}/browser-extension-data/uBlock0@raymondhill.net"
    - copy:
        src: files/uBlock0@raymondhill.net/storage.js
        dest: "{{ profile_path }}/browser-extension-data/uBlock0@raymondhill.net/storage.js"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0644

# UMatrix
- name: download addons
  get_url:
    url: "{{ addon_download }}/{{item.download}}"
    dest: "{{ profile_path }}/extensions/{{item.name}}.xpi"
  with_items:
    - {download: "1166954", name: "uBlock0@raymondhill.net"}
    - {download: "1057194", name: "uMatrix@raymondhill.net."}
    - {download: "1078499", name: "jid1-BoFifL9Vbdl2zQ@jetpack"}
    - {download: "792833", name: "{33c93ccc-ceed-47d2-9645-805ea58c8a07}"}
    - {download: "970953", name: "neaturl@hugsmile.eu"}
    - {download: "727843", name: "skipredirect@sblask"}
    - {download: "957989", name: "{c607c8df-14a7-4f28-894f-29e8722976af}"}
    - {download: "1171317", name: "@testpilot-containers"}
  retries: 5
  delay: 2
  register: addon_result
  until: addon_result is succeeded

- name: create config folder UMatrix
  file:
    state: directory
    path: "{{ profile_path }}/browser-extension-data/uMatrix@raymondhill.net"

- name: copy UMatrix config
  copy:
    src: files/uMatrix@raymondhill.net/storage.js
    dest: "{{ profile_path }}/browser-extension-data/uMatrix@raymondhill.net/storage.js"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

# Decentraleyes
- name: create config folder decentraleyes
  file:
    state: directory
    path: "{{ profile_path }}/browser-extension-data/jid1-BoFifL9Vbdl2zQ@jetpack"

- name: copy dencetraleyes config
  copy:
    src: files/jid1-BoFifL9Vbdl2zQ@jetpack/storage.js
    dest: "{{ profile_path }}/browser-extension-data/jid1-BoFifL9Vbdl2zQ@jetpack/storage.js"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

# Temporary Containers
- name: create config folder temporary containers
  file:
    state: directory
    path: "{{ profile_path }}/browser-extension-data/{c607c8df-14a7-4f28-894f-29e8722976af}"

- name: copy temporary containers config
  copy:
    src: files/{c607c8df-14a7-4f28-894f-29e8722976af}/storage.js
    dest: "{{ profile_path }}/browser-extension-data/{c607c8df-14a7-4f28-894f-29e8722976af}/storage.js"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
