---
- name: create directory "{{ firefox_path }}"
  file:
    state: directory
    path: "{{ firefox_path }}"

- name: copy profiles.ini
  template:
    src: templates/profiles.ini.j2
    dest: "{{ firefox_path }}/profiles.ini"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

# make sure directories for the addons exist
- name: create project directory "{{ profile_path }}/extensions"
  file:
    state: directory
    path: "{{ profile_path }}/extensions"

- name: create project directory {{ profile_path }}/browser-extension-data
  file:
    state: directory
    path: "{{ profile_path }}/browser-extension-data"

- name: download addons
  get_url:
    url: "{{ addon_download }}/{{ item.name }}/addon-{{ item.name }}-latest.xpi"
    dest: "{{ profile_path }}/extensions/{{ item.directory }}.xpi"
  with_items: "{{ addon_list }}"
  retries: 5
  delay: 2
  register: addon_result
  until: addon_result is succeeded

- name: Check if a storage.js exists
  stat:
    path: "files/{{item.directory}}/storage.js"
  delegate_to: 127.0.0.1
  with_items: "{{ addon_list }}"
  register: file_stat

- name: debug
  debug:
    msg: "{{ file_stat.results }}"

- name: create config folders
  file:
    state: directory
    path: "{{ profile_path }}/browser-extension-data/{{ item.item.directory }}"
  with_items: "{{ file_stat.results }}"
  when: item.stat.exists == false

- name: Copy config
  copy:
    src: "files/{{ item.item.directory }}/storage.js"
    dest: "{{ profile_path }}/browser-extension-data/{{ item.item.directory }}/storage.js"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
  with_items: "{{ file_stat.results }}"
  when: item.stat.exists == false
