---
- name: Install packages needed for firefox on Arch Linux
  become: true
  pacman:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - pulseaudio
      - firefox
      - firejail
  retries: 5
  delay: 2
  register: pacman_result
  until: pacman_result is succeeded
  tag: setup
