---
- name: Install packages needed for firefox on Debian
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fonts-font-awesome
      - firefox-esr
  retries: 5
  delay: 2
  register: debian_result
  until: debian_result is succeeded
