---
- name: add chrome folder
  file:
    path: "{{ profile_path }}/chrome"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: add background image
  copy:
    src: files/chrome/firefox.png
    dest: "{{ profile_path }}/chrome/firefox.png"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: add userContent.css
  copy:
    src: files/chrome/userContent.css
    dest: "{{ profile_path }}/chrome/userContent.css"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
