- name: Install packages needed for firefox on fedora
  become: true
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libselinux-python
      - fontawesome-fonts
      - firefox
  retries: 5
  delay: 2
  register: fedora_result
  until: fedora_result is succeeded
