---
- name: Install packages needed for firefox on fedora
  become: true
  dnf:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - libselinux-python
      - firefox
      - firejail
  retries: 5
  delay: 2
  register: fedora_result
  until: fedora_result is succeeded
