---
- name: add firefox esr repo ubuntu
  become: true
  apt_repository:
    repo: ppa:mozillateam/ppa
  when: ansible_distribution == 'Ubuntu'

- name: Install packages needed for firefox
  become: true
  package:
    name: libselinux-python
    state: present
  when:ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat'
  retries: 5
  delay: 2
  register: packages_result
  until: packages_result is succeeded

- name: Install pulseaudio for sound output on arch linux
  become: true
  pacman:
    name: pulseaudio
    state: present
    update_cache: true
  when: ansible_distribution == 'Archlinux'
  retries: 5
  delay: 2
  register: pacman_result
  until: pacman_result is succeeded

- name: Install firefox
  become: true
  package:
    name: firefox-esr
    state: present
  when: ansible_distribution == 'Debian'
  retries: 5
  delay: 2
  register: firefox_esr_result
  until: firefox_esr_result is succeeded

- name: Install firefox
  become: true
  package:
    name: firefox
    state: present
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat' or
        ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
  retries: 5
  delay: 2
  register: firefox_result
  until: firefox_result is succeeded
