---
- name: Install packages needed for firefox
  become: true
  package:
    name: libselinux-python
    state: present
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat'

- name: Install pulseaudio for sound output on arch linux
  become: true
  pacman:
    name: pulseaudio
    state: latest
    update_cache: true
  when: ansible_distribution == 'Archlinux'
