---
- name: add firefox esr repo ubuntu
  become: true
  apt_repository:
    repo: ppa:mozillateam/ppa
  when: ansible_distribution == 'Ubuntu'

- name: Install packages needed for firefox on fedora and redhat
  become: true
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libselinux-python
      - fontawesome-fonts
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat'
  retries: 5
  delay: 2
  register: fedora_result
  until: fedora_result is succeeded

- name: Install packages needed for firefox on Ubuntu and Debian
  become: true
  apt:
    name: fonts-font-awesome
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  retries: 5
  delay: 2
  register: debian_result
  until: debian_result is succeeded

- name: Install packages needed for firefox on Arch Linux
  become: true
  pacman:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - otf-font-awesome
      - pulseaudio
  when: ansible_distribution == 'Archlinux'
  retries: 5
  delay: 2
  register: pacman_result
  until: pacman_result is succeeded

- name: Install firefox
  become: true
  package:
    name: firefox-esr
    state: present
  when: ansible_distribution == 'Debian'
  retries: 5
  delay: 2
  register: firefox_esr_result
  until: firefox_esr_result is succeeded

- name: Install firefox
  become: true
  package:
    name: firefox
    state: present
  when: ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat' or ansible_distribution == 'Ubuntu'
  retries: 5
  delay: 2
  register: firefox_result
  until: firefox_result is succeeded
