# package install
- name: Install packages needed for firefox
  become: yes
  package:
    name: libselinux-python
    state: present

- name: Install pulseaudio for sound output on arch linux
  become: yes
  pacman:
    name: pulseaudio
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Archlinux'
