---
- name: check wether profile already
  find:
    paths: "{{ firefox_path }}"
    patterns: '*.{{ profile_name }}'
    file_type: directory
  register: profile

- name: set old profile as path
  set_fact:
    profile_path: "{{ profile.files[0].path }}"
  when: profile.matched > 0

- name: create directory for config
  file:
    path: "{{ firefox_path }}/{{ profile_hash }}.{{ profile_name }}"
    state: directory
    recurse: true
  when: profile.matched == 0

- name: set new profile as path
  set_fact:
    profile_path: "{{ firefox_path }}/{{ profile_hash }}.{{ profile_name }}"
  when: profile.matched == 0

- name: create directory for config
  template:
    src: templates/profiles.ini
    dest: "{{ firefox_path }}/profiles.ini"
  when: profile.matched == 0
