---
- name: check wether profile already
  find:
    paths: "{{ firefox_path }}"
    patterns: '*.{{ profile_name }}'
    file_type: directory
  register: profile

- debug:
    msg: 
     - "{{ username }}"
     - "{{ firefox_path }}"
     - "{{ profile_name }}"

- name: set old profile as path
  set_fact:
    profile_path: "{{ profile.files[0].path }}"
  when: profile.matched > 0

- name: create directory for config
  command: "firefox -CreateProfile {{ profile_name }} --headless"
  when: not profile.matched
  become: yes
  become_method: su
  become_flags: '-s /bin/sh'
  become_user: "{{ username }}"

- name: check new directory name
  find:
    paths: "{{ firefox_path }}"
    patterns: '*.{{ profile_name }}'
    file_type: directory
  register: new_profile
  when: not profile.matched

- debug:
    msg: "{{ new_profile }}"

- name: set new profile as path
  set_fact:
    profile_path: "{{ new_profile.files[0].path }}"
  when: not profile.matched
