---
- name: Install packages needed for firefox on redhat
  become: true
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - libselinux-python
      - firefox
      - firejail
  retries: 5
  delay: 2
  register: redhat_result
  until: redhat_result is succeeded
