---
- name: add firefox esr repo ubuntu
  become: true
  apt_repository:
    repo: ppa:mozillateam/ppa
  when: ansible_distribution == 'Ubuntu'

- name: Install packages needed for firefox on Ubuntu
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - fonts-font-awesome
      - firefox
      - fontconfig
  retries: 5
  delay: 2
  register: ubuntu_result
  until: ubuntu_result is succeeded
