---
dependency:
  name: galaxy
driver:
  name: docker
ansible:
  verbose: vv

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: ansible-ubuntu-16-04-lts
    image: ubuntu
    image_version: '16.04'
  - name: ansible-ubuntu-1704
    image: ubuntu
    image_version: '17.04'
  - name: ansible-ubuntu-18-04-lts
    image: ubuntu
    image_version: '18.04'

  - name: ansible-arch-latest
    image: archlinux/base
    image_version: latest
    command: /lib/systemd/systemd
    privileged: true

  - name: ansible-centos-latest
    image: centos
    image_version: latest
    command: /usr/lib/systemd/systemd
    privileged: true

  - name: ansible-debian-latest
    image: debian
    image_version: latest

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
